# Generated by Django 4.0.4 on 2022-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sales_tax',
            field=models.IntegerField(verbose_name='ТТН'),
        ),
    ]
