# Generated by Django 4.0.4 on 2022-06-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shipping_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='buyer',
            field=models.CharField(blank=True, max_length=250, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='dispatcher',
            field=models.CharField(blank=True, max_length=250, verbose_name='Диспетчер'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='driver',
            field=models.CharField(blank=True, max_length=250, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='factory',
            field=models.CharField(blank=True, max_length=250, verbose_name='Завод'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.CharField(blank=True, max_length=250, verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='product',
            field=models.CharField(blank=True, max_length=250, verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='purchase_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sales_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sales_tax',
            field=models.PositiveIntegerField(blank=True, verbose_name='ТТН'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='seller',
            field=models.CharField(blank=True, max_length=250, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='supplier',
            field=models.CharField(blank=True, max_length=250, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='waybill',
            field=models.CharField(blank=True, choices=[('1', 'Да'), ('0', 'Нет')], default='0', max_length=250, verbose_name='Накладная'),
        ),
    ]
