# Generated by Django 4.0.4 on 2022-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_alter_shipping_address_alter_shipping_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='waybill',
            field=models.CharField(choices=[('1', 'Да'), ('0', 'Нет')], default='0', max_length=250, verbose_name='Накладная'),
        ),
    ]
