# Generated by Django 4.0.4 on 2022-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('supplier', models.CharField(max_length=250, verbose_name='Поставщик')),
                ('factory', models.CharField(max_length=250, verbose_name='Завод')),
                ('order', models.CharField(max_length=250, verbose_name='Приказ')),
                ('seller', models.CharField(max_length=250, verbose_name='Продавец')),
                ('buyer', models.CharField(max_length=250, verbose_name='Покупатель')),
                ('waybill', models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], default='N', max_length=250, verbose_name='Накладная')),
                ('sales_tax', models.IntegerField(max_length=250, verbose_name='ТТН')),
                ('product', models.CharField(max_length=250, verbose_name='Продукция')),
                ('quantity', models.IntegerField(default=1, max_length=250, verbose_name='Количество')),
                ('purchase_price', models.IntegerField(verbose_name='Цена покупки')),
                ('sales_price', models.IntegerField(verbose_name='Цена продажи')),
                ('delivery_price', models.IntegerField(verbose_name='Цена доставки')),
                ('driver', models.CharField(max_length=250, verbose_name='Водитель')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('dispatcher', models.CharField(max_length=250, verbose_name='Диспетчер')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
            },
        ),
    ]
