# Generated by Django 4.0.5 on 2022-06-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_alter_shipping_options_alter_shipping_sales_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-id'], 'verbose_name': 'Отгрузку', 'verbose_name_plural': 'Отгрузки'},
        ),
    ]
