# Generated by Django 4.0.4 on 2022-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipping_quantity_alter_shipping_sales_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='waybill',
            field=models.CharField(choices=[('1', 'Да'), ('0', 'Нет')], default='0', max_length=250, verbose_name='Накладная'),
        ),
        migrations.AlterModelTable(
            name='shipping',
            table='Таблица отгрузок',
        ),
    ]
