# Generated by Django 4.0.4 on 2022-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_alter_shipping_waybill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-id'], 'verbose_name': 'Отгрузка', 'verbose_name_plural': 'Отгрузки'},
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sales_tax',
            field=models.CharField(blank=True, max_length=250, verbose_name='ТТН'),
        ),
    ]
