# Generated by Django 4.0.5 on 2022-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_alter_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, default='0', verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='purchase_price',
            field=models.PositiveIntegerField(blank=True, default='5000', verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='sales_price',
            field=models.PositiveIntegerField(blank=True, default='0', verbose_name='Цена продажи'),
        ),
    ]
