# Generated by Django 4.0.5 on 2022-06-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_alter_shipping_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipping',
            table='SHHHIP',
        ),
    ]
