# Generated by Django 4.0.5 on 2022-06-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_alter_shipping_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipping',
            table=None,
        ),
    ]
